name: Test Output
on: [push]
jobs:
  test_program_output:
    name: diff_outputs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: create test output 1
        run: python find_lowest_number.py test_data/test1_input.txt test_data/test1_output
      - name: create test output 2
        run: python find_lowest_number.py test_data/test2_input.txt test_data/test2_output
      - name: create test output 3
        run: python find_lowest_number.py test_data/test3_input.txt test_data/test3_output


      - name: diff output
        run: echo hello world
